### ISSUE TITLE
small problem booting using (npm run dev)

### ISSUE THREAD

**Issue by davi-sant** [andremalveira/create-html5-app#1]
speak @andremalveira  , man your app is very cool, it has easy interaction with the developers congratulations.
  - in my use I had only one problem, of a simple level because it doesn't affect much in the application's interaction.
- [Error] when I go to upload a local server using command provided by documentation
```js
npm run dev 
```
  I get an (error) that the json file is not present in the root of the directory, making it impossible to initialize it.

note: the error was reproduced using only npm yarn was not tested in this case
- operating system: windows 11
- node in version: v16.17.0
- npm in version: v8.19.1

**Comment by andremalveira** [comment]
Hi @davi-sant, Thanks for letting me know, in this first version for being a simple example in HTML5, it doesn't have a command to start the project, it was just a mistake in the writing of readme.md, but it's already fixed! 😁👍

**Comment by davi-sant** [comment]
> Oi@davi-sant, Obrigado por avisar, nesta primeira versão por ser um exemplo simples em HTML5, não tem comando para iniciar o projeto, foi apenas um erro na escrita do readme.md, mas já está corrigido!😁👍
